### PR TITLE
Rugpull disclosure system

### PR DESCRIPTION
**Pull request by bloated-devish**
This PR is a draft CIP on responsible rugpull disclosure by creators.

### CODE REVIEW

**Comment by HPaulson** [comment]
This should be a discussion first! Checkout the readme :)

**Comment by bloated-devish** [comment]
> This should be a discussion first! Checkout the readme :)

Acknowledged. I updated my discussion post. This PR for now can be left as is (or I'll abandon it if the devs want to keep the PR queue clean or if the discussion makes it clear the CIP can't work).

**Comment by tijno** [comment]
@bloated-devish id say close it so CIP PRs stay clean.

**Comment by dgsus** [comment]
+1 keeping this clean

**Comment by maebeam** [comment]
Closing this until there is more discussion: https://github.com/bitclout/cips/discussions/15

**Pull request closed without merging**
